### PR TITLE
Create example for parallel server

### PR DESCRIPTION
**Pull request by SirRade**
This server sends and receives messages independently

### CODE REVIEW

**Comment by daboross** [comment]
I think this needs to add `futures-cpupool` as a dev-dependency in `Cargo.toml` in order to compile.

**Comment by SirRade** [comment]
Thanks for the reminder.
I'm brewing up a better example anyways so people can use it a scalable startpoint. Gonna fix the travis build when that is ready.

**Comment by illegalprime** [comment]
Hey this is awesome! Thanks a bunch, travis was being weird but now it's fixed. Feel free to rebase on top of the latest changes.

**Comment by SirRade** [comment]
Hmm, any idea why my `cargo fmt` with your .rustfmt.toml is generating a different output than travis?

**Comment by SirRade** [comment]
Feel free to merge it now. I wrote this example with a game server in mind.

As I am not that experienced in working with futures, I most probably made some things way more complicated that they could be.  But hey, it's parallel and scalable to as many users as you like :)

**Comment by SirRade** [comment]
I think Travis bugged out there.
For me it says right here that the build is still running
image
While on the actual build page it says it finished 24 ago
image

**Comment by illegalprime** [comment]
Thank you again!

**Comment by bobogei81123** [comment]
Regarding the code in this example:
```rust
send_channel_in.for_each(move |(id, msg): (Id, String)| {
	let connections = connections.clone();
	let sink = connections.write()
	                      .unwrap()
	                      .remove(&id)
	                      .expect("Tried to send to invalid client id",);

	println!("Sending message '{}' to id {}", msg, id);
	let f = sink.send(OwnedMessage::Text(msg))
	            .and_then(move |sink| {
		                      connections.write().unwrap().insert(id, sink);
		                      Ok(())
		                     });
	remote.spawn(move |_| f.map_err(|_| ()));
	Ok(())
})
.map_err(|_| ())
```
Isn't it possible that the last message haven't been sent completely but the `send_channel_in` receive another message to the same client? The sink of the client would be removed from the hashmap temporary then.

**Comment by SirRade** [comment]
Good catch, I think you're right. Unfortunately I don't have time right now to fix it. Do you wanna give it a try?

**Comment by bobogei81123** [comment]
I've create the pull request #148, but as a newbee to tokio and future, maybe you could check if my fix is correct.

**Pull request merged**
