### PR TITLE
Bump bitflags to 0.9 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by illegalprime** [comment]
@Eijebong looks good, when this test passes I'll merge.

**Comment by Eijebong** [comment]
Do you want me to fix those rustfmt failures ? They are not related to this PR but I can do it in a separate commit

**Comment by illegalprime** [comment]
oh jeez, that formatter is getting annoying. I can do it, since it's not related it wouldn't make sense here.
Just rebase on top of the last commit and everything should be OK

**Comment by Eijebong** [comment]
Could you also publish it on crates.io ? :)

**Comment by illegalprime** [comment]
Yeah np

**Comment by illegalprime** [comment]
@Eijebong published

**Comment by Eijebong** [comment]
Thank you !

**Pull request merged**
