### PR TITLE
Update dependencies with breaking changes

### PR DESCRIPTION
**Pull request by SimonSapin**
Please also publish on crates.io

CC https://github.com/servo/servo/pull/8446

### CODE REVIEW

**Comment by SimonSapin** [comment]
This requires the same change in hyper to be published on crates.io

**Comment by illegalprime** [comment]
Unfortunately (as mentioned in #55) an update in `libc` is breaking the build on windows (seanmonstar/num_cpus#15).
Although this issue was closed recently so maybe we are good to go? (@cyderize?)
Anyway, it's incredibly humbling that you guys are using this!

**Comment by cyderize** [comment]
Thanks for this, @SimonSapin!

@illegalprime, `num_cpus` has been fixed now (v0.2.9), so I should be able to update the crate.

**Comment by illegalprime** [comment]
cool. thank you @cyderize! I'm finally on break, maybe I'll send some PRs your way.

**Pull request merged**
