### PR TITLE
Use the ? operator

### PR DESCRIPTION
**Pull request by ashfordneil**
See #110 - replaced `try!` with `?`

Thoughts?

### CODE REVIEW

**Comment by illegalprime** [comment]
`git grep 'try!'` doesn't show anything, I'm satisfied! Thanks!
Please rebase your latest commit on top of the current master then force push, also remember to run `cargo fmt` (install it with `cargo install rustfmt`) so the diff doesn't show any style changes, only functional changes.

**Comment by ashfordneil** [comment]
I did run cargo fmt, and I fixed the above errors. However, there was some "force --push" involved and travis doesn't seem to like that.

**Comment by illegalprime** [comment]
Hey @ashfordneil thanks for the `cargo fmt`! Can you please remove these commits from your PR:

1. removed rust serialize 73f0525
2. Merge branch 'master' of https://github.com/cyderize/rust-websocket 692773a

After that it'll be good to merge! Thanks!

**Comment by illegalprime** [comment]
@ashfordneil could you rebase on top of the new changes?

**Comment by ashfordneil** [comment]
Re: cargo fmt issues -- I've been running rustfmt 0.8.4, but travis uses 0.8.1. By disabling the cache, I can get travis to use the up-to-date version (which says the code is fine), but I don't know how to cache the up-to-date version. Any ideas on what to do about this?

**Comment by illegalprime** [comment]
@ashfordneil nice catch, yeah to avoid these issues I think cargo should either always update and not cache OR it should cache and always use one version.

**Pull request merged**
