### PR TITLE
Added util functions parse_url and parse_url_str and introduced new W…

### PR DESCRIPTION
**Pull request by Nashenas88**
Added util functions parse_url and parse_url_str and introduced new WebSocketError::WebSocketUrlError

### CODE REVIEW

**Comment by Nashenas88** [comment]
There are still some tests to be written, but I wanted the code up earlier so we could review it if you think I should make some changes. Also, I'd like your input into how I should be writing tests. I copied the format in util/header.rs, but I'm not sure if that's where you want to keep going.

**Comment by cyderize** [comment]
It looks pretty good to me.

I'm not too concerned about the format of the tests, as long as they, well, test the function.
Thanks for this.

**Comment by cyderize** [comment]
This is looking good now. When you're ready to merge, can you squash the commits and let me know?

Thanks

**Comment by Nashenas88** [comment]
@cyderize The tests are done, commits squashed, and some code cleanup. I found one bug where the initial forward slash on the resource was missing for non-empty paths, and I simplified `parse_url_str` with `try!` and `Result`'s `.map_err` function.

**Comment by cyderize** [comment]
This is awesome! Thanks so much

**Pull request merged**
