### PR TITLE
Update bitflags to 0.7

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
This supersedes #77.

**Comment by cyderize** [comment]
Thanks!

**Comment by nox** [comment]
Thanks for merging it! Will you make a new release?

**Comment by cyderize** [comment]
Yes, it should be updated on crates.io now

**Comment by nox** [comment]
@cyderize I've been informed that bitflags >=0.6 isn't compatible with Rust <1.8. Do you want me to make a new bump that allows bitflags 0.5-0.7?

**Pull request merged**
